### ISSUE TITLE
Not working for new @sentry v4 beta versions

### ISSUE THREAD

**Issue by mcrawshaw** [captbaritone/raven-for-redux#82] opened 2018-08-02 05:06 UTC
API has changed.
`Uncaught TypeError: e.setDataCallback is not a function`

**Comment by captbaritone** [comment] 2018-08-04 01:26
Thanks for the heads up!

**Comment by captbaritone** [comment] 2018-08-07 20:40
I've started looking into this and filed an issue with Sentry to see if we can get support for lazyily setting scope: https://github.com/getsentry/sentry-javascript/issues/1281#issuecomment-411194452

**Comment by deammer** [comment] 2018-09-14 18:09
I don't know if this is useful, but I wrote a tiny middleware that logs breadcrumbs to Sentry:

```js
import thunk from 'redux-thunk';
import { applyMiddleware, createStore, compose } from 'redux';
import { init, addBreadcrumb } from '@sentry/browser';

// Sentry middleware
 const sentryReporter = store => next => action => {
  addBreadcrumb({
    message: action.type,
    category: 'redux action',
    level: 'info',
    data: {
      payload: action.payload
    }
  });
  return next(action);
};

// Create the store with our Sentry middleware
const reduxStore = createStore(
  rootReducer,
  composeEnhancers(applyMiddleware(thunk, sentryReporter))
);

// Initialize Sentry
init({
  dsn: process.env.SENTRY_URL,
  environment: process.env.NODE_ENV
});
```

After reading the comments in getsentry/sentry-javascript#1281, I first wrote an "integration" that used `store.dispatch()` to log to Senty, but I felt like that was obfuscating things too much for my taste. A middleware felt cleaner because it chains functions instead of monkeypatching the `dispatch` call.

**Comment by joan-saum** [comment] 2019-08-09 08:00
Any news about this issue @captbaritone ?

**Comment by captbaritone** [comment] 2019-08-14 20:23
I don’t think I’ll be able to find time to work on this. If someone wants to open a PR, I can review, but this might be a good time for someone to fork. Sorry folks.

**Comment by sweatherall** [comment] 2019-12-17 22:43
@captbaritone are there any updates? I just upgraded from react-native-sentry to @sentry/react-native and I am seeing the `TypeError: Raven.setDataCallback is not a function` in my Sentry logs, and actually it is preventing the app from even loading :(. We would love to continue to use raven/get the redux actions back in the breadcrumbs. LMK if there is anything to do! Thanks!

**Comment by captbaritone** [comment] 2019-12-18 04:23
I've written a version that seems to work as part of my Webamp project: https://github.com/captbaritone/webamp/pull/956

My plan is to ship it there to validate that it will work over here. If you want to copy paste that file into your project and see if it works, I'd love to hear what if any problems you encounter.

I think the only real hard work of adopting that code in this code base will be updating the tests, since the existing tests are tightly coupled to the internals of Raven.

**Comment by captbaritone** [comment] 2019-12-19 04:44
Actually, this is a dupe of #93. Check out https://github.com/vidit-sh/redux-sentry-middleware it looks like the same idea I was going to do, except better.

**Closed by captbaritone** 2019-12-19 04:44 UTC
